[package]
name = "raspi4-net"
version = "0.1.0"
edition = "2021"

[dependencies]
axstd = { path = "../../../ulib/axstd", optional = true }
log = "0.4.0"
bcm2711-hal = { path = "../../../crates/bcm2711-hal" }

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2"
