[package]
name = "raspi4-net"
version = "0.1.0"
edition = "2021"

[dependencies]
axstd = { path = "../../../ulib/axstd", optional = true }

arm_pl011 = { version = "0.1.0", path = "../../../crates/arm_pl011" }
arm_gpio = { version = "0.1.0", path = "../../../crates/arm_gpio/" }
