[package]
name = "arceos-udpserver"
version = "0.1.0"
edition = "2021"
authors = ["Dashuai Wu <wudashuaijss@foxmail.com>"]

[dependencies]
axstd = { path = "../../../ulib/axstd", features = ["net", "driver-bcm54213pe"] }
log = "0.4.0"
