[package]
name = "axdtb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
hermit-dtb = "0.1.1"
axlog = { path = "../axlog" }